### ISSUE TITLE
Feature request: releases for humble and rolling

### ISSUE THREAD

**Issue by cmraaron** [nobleo/paho.mqtt.c-release#1]
I've been using this in galactic, thank you for your efforts.
It would be great to have these in humble and rolling also

**Comment by Timple** [comment]
Yes, this can be done, would you mind pinging me in two weeks if I've failed to do so? 🙂

**Comment by Timple** [comment]
Actually, I remember now the reason for not doing this in the first place. It's already released for ubuntu 22.04.

`sudo apt-get install libpaho-mqttpp-dev` should do the trick as well. Would you mind verifying if this works for you?
The only reason I added these to the ROS repositories was because they where missing from ubuntu 20.04.

**Comment by cmraaron** [comment]
ah, yes.  perfect.  Thank you :+1:
